require('dotenv').config();
const express=require('express'),cors=require('cors'),helmet=require('helmet'),rateLimit=require('express-rate-limit'),jwt=require('jsonwebtoken'),bcrypt=require('bcryptjs'),{Pool}=require('pg'),multer=require('multer'),path=require('path'),fs=require('fs');
const app=express();
const PORT=Number(process.env.PORT||10000);
const DATABASE_URL=process.env.DATABASE_URL;
const JWT_SECRET=process.env.JWT_SECRET;
if(!DATABASE_URL) console.warn('DATABASE_URL não configurado.');
if(!JWT_SECRET||JWT_SECRET==='CHANGE_ME') console.warn('JWT_SECRET não configurado.');
const pool=new Pool({connectionString:DATABASE_URL,ssl:DATABASE_URL?{rejectUnauthorized:false}:false});
app.use(helmet({crossOriginResourcePolicy:false}));
app.use(cors({origin:process.env.CORS_ORIGIN||'*'}));
app.use(express.json({limit:'2mb'}));
const uploadDir=path.join(__dirname,'../uploads'); fs.mkdirSync(uploadDir,{recursive:true});
const upload=multer({dest:uploadDir,limits:{fileSize:15*1024*1024},fileFilter:(req,file,cb)=>cb(null,/^(image\/|video\/)/.test(file.mimetype))});
app.use('/uploads',express.static(uploadDir));
app.use('/api/',rateLimit({windowMs:15*60*1000,max:240,standardHeaders:true,legacyHeaders:false}));
function clean(v,max=2000){return String(v??'').trim().slice(0,max)}
async function initDb(){await pool.query(`CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY, role TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL); CREATE TABLE IF NOT EXISTS alerts(id BIGSERIAL PRIMARY KEY, source_type TEXT NOT NULL, type TEXT NOT NULL, level TEXT NOT NULL, area TEXT NOT NULL, status TEXT NOT NULL, occurrence_mode TEXT, message TEXT NOT NULL, source TEXT, geometry JSONB, geometry_kind TEXT, geometry_radius DOUBLE PRECISION, issued_at TIMESTAMPTZ NOT NULL, starts_at TIMESTAMPTZ, expires_at TIMESTAMPTZ, active BOOLEAN DEFAULT TRUE); CREATE TABLE IF NOT EXISTS reports(id BIGSERIAL PRIMARY KEY,type TEXT NOT NULL,area TEXT,message TEXT NOT NULL,media_url TEXT,created_at TIMESTAMPTZ NOT NULL,status TEXT DEFAULT 'pending'); CREATE TABLE IF NOT EXISTS audit_logs(id BIGSERIAL PRIMARY KEY,action TEXT,alert_id BIGINT,actor_id INTEGER,created_at TIMESTAMPTZ NOT NULL);`); const u=await pool.query('SELECT id FROM users WHERE role=$1',['admin']); if(!u.rowCount){const hash=await bcrypt.hash(process.env.TEAM_PASSWORD||'2013',12);await pool.query('INSERT INTO users(role,password_hash,created_at) VALUES($1,$2,NOW())',['admin',hash]);console.log('Equipe inicial criada.');}}
function auth(req,res,next){try{const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return res.status(401).json({error:'unauthorized'});if(!JWT_SECRET||JWT_SECRET==='CHANGE_ME')return res.status(503).json({error:'server_secret_not_configured'});req.user=jwt.verify(h.slice(7),JWT_SECRET);next()}catch(e){res.status(401).json({error:'unauthorized'})}}
app.get('/api/health',async(req,res)=>res.json({ok:true,service:'Mendes Strom',time:new Date().toISOString()}));
app.get('/api/config',(req,res)=>res.json({service:'Mendes Strom',live:true,officialAlertsIntegrated:false,pushConfigured:Boolean(process.env.FCM_PROJECT_ID)}));
app.post('/api/auth/login',async(req,res)=>{try{const u=(await pool.query('SELECT * FROM users WHERE role=$1',['admin'])).rows[0];if(!u||!(await bcrypt.compare(clean(req.body.password,200),u.password_hash)))return res.status(401).json({error:'invalid_credentials'});if(!JWT_SECRET||JWT_SECRET==='CHANGE_ME')return res.status(503).json({error:'server_secret_not_configured'});const token=jwt.sign({sub:u.id,role:u.role},JWT_SECRET,{expiresIn:'8h'});res.json({token,expiresIn:28800})}catch(e){res.status(500).json({error:'login_failed'})}});
app.get('/api/alerts',async(req,res)=>{try{const area=clean(req.query.area||'Todo Mendes',100);const includeInactive=req.query.includeInactive==='true' && !!(req.headers.authorization);const q=includeInactive?'SELECT id,source_type as "sourceType",type,level,area,status,occurrence_mode as "occurrenceMode",message,source,geometry,geometry_kind as "geometryKind",geometry_radius as "geometryRadius",issued_at as "issuedAt",starts_at as "startsAt",expires_at as "expiresAt",active FROM alerts WHERE (area=$1 OR area=\'Todo Mendes\') ORDER BY issued_at DESC':'SELECT id,source_type as "sourceType",type,level,area,status,occurrence_mode as "occurrenceMode",message,source,geometry,geometry_kind as "geometryKind",geometry_radius as "geometryRadius",issued_at as "issuedAt",starts_at as "startsAt",expires_at as "expiresAt",active FROM alerts WHERE active=TRUE AND (area=$1 OR area=\'Todo Mendes\') AND (expires_at IS NULL OR expires_at>NOW()) ORDER BY issued_at DESC';res.json((await pool.query(q,[area])).rows)}catch(e){res.status(500).json({error:'alerts_failed'})}});
app.post('/api/alerts',auth,async(req,res)=>{try{const type=clean(req.body.type,80),level=clean(req.body.level,30),area=clean(req.body.area,100),status=clean(req.body.status,30),occurrenceMode=clean(req.body.occurrenceMode,30),message=clean(req.body.message,4000);const levels=['green','yellow','orange','red','black'];const areas=['Todo Mendes','Centro','Ponte do Rocha','Cinco Lagos','Martins Costa','Morsing','Água Fria','Humberto Antunes','Vila Mariana','Santa Rosa','Santa Rita','Independência','Oscar Rudge','Jabuticabeiras','Boa Esperança','Fim do Ponto','Coqueiros'];if(!type||!level||!area||!status||!message)return res.status(400).json({error:'missing_fields'});if(!levels.includes(level)||!areas.includes(area)||!['forecast','observed'].includes(status))return res.status(400).json({error:'invalid_fields'});if(type==='Tornado observado'&&level==='black'&&status!=='observed')return res.status(400).json({error:'black_tornado_requires_observed'});const startsAt=req.body.startsAt?new Date(req.body.startsAt):new Date();const expiresAt=req.body.endsAt?new Date(req.body.endsAt):null;const geometry=req.body.geometry??null;const result=await pool.query('INSERT INTO alerts(source_type,type,level,area,status,occurrence_mode,message,source,geometry,geometry_kind,geometry_radius,issued_at,starts_at,expires_at,active) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,NOW(),$12,$13,TRUE) RETURNING id',['team',type,level,area,status,occurrenceMode,message,null,geometry,req.body.geometryKind||null,req.body.geometryRadius||null,startsAt,expiresAt]);const id=result.rows[0].id;await pool.query('INSERT INTO audit_logs(action,alert_id,actor_id,created_at) VALUES($1,$2,$3,NOW())',['create_team_alert',id,req.user.sub]);res.status(201).json({id})}catch(e){console.error(e);res.status(500).json({error:'publish_failed'})}});
app.patch('/api/alerts/:id',auth,async(req,res)=>{try{const id=Number(req.params.id);const a=await pool.query('SELECT id FROM alerts WHERE id=$1',[id]);if(!a.rowCount)return res.sendStatus(404);const active=req.body.active===true;await pool.query('UPDATE alerts SET active=$1 WHERE id=$2',[active,id]);await pool.query('INSERT INTO audit_logs(action,alert_id,actor_id,created_at) VALUES($1,$2,$3,NOW())',[active?'activate':'close',id,req.user.sub]);res.json({ok:true})}catch(e){res.status(500).json({error:'update_failed'})}});
app.delete('/api/alerts/:id',auth,async(req,res)=>{try{const id=Number(req.params.id);await pool.query('DELETE FROM alerts WHERE id=$1',[id]);await pool.query('INSERT INTO audit_logs(action,alert_id,actor_id,created_at) VALUES($1,$2,$3,NOW())',['delete',id,req.user.sub]);res.json({ok:true})}catch(e){res.status(500).json({error:'delete_failed'})}});
app.post('/api/reports',upload.single('media'),async(req,res)=>{try{const type=clean(req.body.type,80),area=clean(req.body.area,100),message=clean(req.body.message,4000),mediaUrl=req.file?`/uploads/${req.file.filename}`:clean(req.body.mediaUrl,1000);if(!type||!message)return res.status(400).json({error:'missing_fields'});const r=await pool.query('INSERT INTO reports(type,area,message,media_url,created_at) VALUES($1,$2,$3,$4,NOW()) RETURNING id',[''+type,area,message,mediaUrl]);res.status(201).json({id:r.rows[0].id,status:'pending'})}catch(e){res.status(500).json({error:'report_failed'})}});
app.get('/api/reports',auth,async(req,res)=>res.json((await pool.query('SELECT * FROM reports ORDER BY created_at DESC')).rows));
app.patch('/api/reports/:id',auth,async(req,res)=>{const status=clean(req.body.status,30);if(!['pending','verified','rejected'].includes(status))return res.status(400).json({error:'invalid_status'});await pool.query('UPDATE reports SET status=$1 WHERE id=$2',[status,Number(req.params.id)]);res.json({ok:true})});
app.get('/api/history',auth,async(req,res)=>res.json((await pool.query('SELECT * FROM alerts ORDER BY issued_at DESC LIMIT 500')).rows));
initDb().then(()=>app.listen(PORT,'0.0.0.0',()=>console.log(`Mendes Strom API em 0.0.0.0:${PORT}`))).catch(e=>{console.error(e);process.exit(1)});
